name: chat
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" #">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  web_socket_channel: ^2.4.0 #web_socket_channel: ^1.1.0
  bloc_test: ^9.1.4 #bloc_test: ^7.0.2
  uuid: ^4.0.0 #uuid: 2.2.2
  hydrated_bloc: ^9.1.2 #hydrated_bloc: 6.1.0
  dio: ^5.3.2 #dio: 3.0.10
  logger: ^2.0.2 #logger: 0.9.4
  async: ^2.11.0 #async: 2.4.2
  rxdart: ^0.27.7 #rxdart: 0.25.0
  path_provider: ^2.1.1
  flutter_localizations: { sdk: flutter }
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6



flutter:
  generate: true
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  