name: chat
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.11.0
  base_codecs: ^1.0.1
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  bloc_test: ^9.1.4
  cross_file: ^0.3.3+5
  cupertino_icons: ^1.0.6
  data_queue: ^1.0.2
  de_log: ^1.0.0
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations: { sdk: flutter }
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  logger: ^2.0.2
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  share_plus: ^4.1.0
  stream_transform: ^2.1.0
  uuid: ^4.0.0
  web_socket_channel: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3



flutter:
  generate: true
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  